load("//Config:buck_rule_macros.bzl", "static_library")

apple_resource(
    name = "AssetXib",
    visibility = ["PUBLIC"],
    dirs = [],
    files = glob([
        "**/*.xib",
    ]),
)

static_library(
    name = "ItemListUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        ":AssetXib",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/MergeLists:MergeLists",
        "//submodules/TextFormat:TextFormat",
        "//submodules/Markdown:Markdown",
        "//submodules/ProgressNavigationButtonNode:ProgressNavigationButtonNode",
        "//submodules/SwitchNode:SwitchNode",
        "//submodules/AnimatedStickerNode:AnimatedStickerNode",
        "//submodules/TelegramAnimatedStickerNode:TelegramAnimatedStickerNode",
        "//submodules/CheckNode:CheckNode",
        "//submodules/SegmentedControlNode:SegmentedControlNode",
        "//submodules/AccountContext:AccountContext",
        "//submodules/AnimationUI:AnimationUI",
        
        "//submodules/HL/Repo:Repo",
        "//submodules/HL/Language:Language",
        "//submodules/HL/Model:Model",
        "//Pods/RxSwift:RxSwift",
        "//Pods/RxCocoa:RxCocoa",
        "//Pods/Then:Then",
        "//submodules/HL/HL:HL",
        "//submodules/HL/Extension:Extension",
        "//submodules/HL/Account:Account",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
